### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Quintus** [amberbit/prawn-fast-png#4]
Hi there, 

The gem's main file `fast_png.rb` is set to be readable just by owner and group: 

```
$ ls -l /opt/rubies/ruby-1.9.2-p290/lib/ruby/gems/1.9.1/gems/prawn-fast-png-0.2.3/lib/prawn
insgesamt 8
-rw-r----- 1 root root  169 16. Jul 15:50 fast_png.rb
drwxr-xr-x 2 root root 4096 16. Jul 15:50 images
```

If someone installs gems as root (as I do) in order to make them available to other users, this is bad because Ruby doesn't find the file: 

```
irb(main):001:0> require "prawn"
=> true
irb(main):002:0> require "prawn/fast_png"
LoadError: no such file to load -- prawn/fast_png
    from /opt/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `require'
    from /opt/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
    from /opt/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from (irb):2
    from /opt/rubies/ruby-1.9.2-p290/bin/irb:12:in `<main>'
irb(main):003:0> 
```

OS: Arch Linux
ruby -v: `ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]`
RubyGems version: 1.8.5

Valete, 
Quintus

**Comment by krzyzanowskim** [comment]
got the same on mac. huh.

**Comment by rpmoore** [comment]
I think it's an issue with how the gem was packaged.  If a new gem could be uploaded that had the correct permissions this would go away.

**Comment by dignoe** [comment]
Anyone find a fix for this yet? I'm seeing this behavior on Amazon Elastic Beanstalk.

**Comment by dignoe** [comment]
I ended up forking the repo, changing the permissions, and loading the gem through git.

**Comment by jteneycke** [comment]
Thanks @dignoe ! 

If anyone else out there needs jruby support, @agworld made a fork that is compatible. https://github.com/agworld/prawn-fast-png
